### PR TITLE
Fix a bug in the swap card. 

### PR DESCRIPTION
**Pull request by valentinmadrid**
Also reset amount to 0 when selecting new from item.

### CODE REVIEW

**Comment by buffalojoec** [comment]
It still doesn't seem to work properly when clicking the double-arrow, and you took out the rounding I had in there

**Comment by valentinmadrid** [comment]
I rounded the display now, but i don't see why swapping them shouldn't work, for me it gives the same rates as if i go and change the amount(which was the problem before).

**Comment by valentinmadrid** [comment]
The thing that gives slightly different rates than the initial amount when swapping two times are the decimals, and the fact that a price doesn't go in the same direction depending on liquidity for different tokens.

**Comment by buffalojoec** [comment]
Ahh I see what you mean. I'm totally good with the reverting to 0 when you click a new token, I think we should somehow fix the arrow "flop" function. 
Seems, to your point, we're incrementing by a whole number so when things are reversed there's a little decimal action in play.
Ultimately, I would be ok with things reverting to 0 after the arrow "flop" too - just so we can stop screwing with it lol

**Pull request closed without merging**
